sudo: false
language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
before_script:
  - mkdir build
  - mkdir build/coverage
#  - composer self-update
  - composer install --dev
after_success:
  - travis_retry php vendor/bin/coveralls -v
